import type { Metadata } from 'next'
import { Open_Sans as FontSans } from 'next/font/google'
import './globals.css'
import Providers from '@/app/providers'
import { cn } from '@/lib/utils'

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={cn(
          'bg-background h-screen font-sans antialiased',
          fontSans.variable
        )}
      >
        <Providers>
          <main className='h-screen'>{children}</main>
        </Providers>
      </body>
    </html>
  )
}
